module AST.Pass;
import corelib;
import LLIR.IR;
import AST.Tree;
import AST.API;
import cpuf.printf;
import logging;
import constants;
import std;
void AST::TreePass::removeEmptyRule(AST::Tree &ast) {
    auto &treeMap = ast.getTreeMap();
    for (auto it = treeMap.begin(); it != treeMap.end();) {
        auto &[name, value] = *it;
        if (value.rule_members.empty()) {
            it = treeMap.erase(it);
            continue;
        }
        it++;
    }
}
auto AST::TreePass::inlineGroup(AST::RuleMemberGroup group, stdu::vector<std::shared_ptr<AST::RuleMember>> &members, stdu::vector<std::shared_ptr<AST::RuleMember>>::iterator toInsert)
    -> stdu::vector<std::shared_ptr<AST::RuleMember>>::iterator // group must be copy else on element insertion iterators will invalidate
{
    // recursively inline nested groups
    for (std::size_t i = 0; i < group.values.size(); ++i) {
        if (group.values[i]->isGroup() && group.values[i]->quantifier == '\0') {
            auto nested = group.values[i]->getGroup(); // copy to avoid stale ref
            inlineGroup(nested, group.values, group.values.begin() + i);
            i += nested.values.size(); // move past inserted
        }
    }
    // inline this group
    return members.insert(toInsert, group.values.begin(), group.values.end()) + static_cast<stdu::vector<std::shared_ptr<AST::RuleMember>>::difference_type>(group.values.size());
}
void AST::TreePass::inlineSingleGroups(AST::Tree &ast) {
    for (auto &[name, value] : ast.getTreeMap()) {
        for (auto it = value.rule_members.begin(); it != value.rule_members.end(); /* no increment here */) {
            if ((*it)->isGroup() && (*it)->quantifier == '\0' && (*it)->prefix.empty()) {
                auto group = (*it)->getGroup(); // make a copy
                it = value.rule_members.erase(it); // erase the group first
                it = inlineGroup(group, value.rule_members, it); // insert unwrapped group
                continue; // check inserted group members
            }
            ++it;
        }

    }
}
void AST::TreePass::literalsToToken(
    stdu::vector<std::shared_ptr<AST::RuleMember>> &literals,
    std::size_t &count,
    stdu::vector<std::pair<stdu::vector<std::string>, AST::Rule>> &toInsert,
    stdu::vector<std::pair<std::shared_ptr<AST::RuleMember>, std::shared_ptr<AST::RuleMember>>> &generated
    ) {
    for (auto &member_ptr : literals) {
        auto &member = *member_ptr;
        if (member.isString() || member.isHex() || member.isBin() || member.isEscaped() || member.isCsequence()) {
            auto find_it = std::find_if(generated.begin(), generated.end(), [&](const std::pair<std::shared_ptr<AST::RuleMember>, std::shared_ptr<AST::RuleMember>> &pair) {
                return *pair.first == member;
            });
            if (find_it != generated.end()) {
                member.value = find_it->second->value; // Use the generated member
            } else {
                // create new token
                stdu::vector<std::string> new_name = {"AUTO_" + std::to_string(count++)};
                auto mem_copy_for_generated = std::make_shared<AST::RuleMember>(member);
                auto newRuleMember = member;
                member.value = AST::RuleMemberName {.name = new_name};
                member.isAutoGenerated = true;
                AST::Rule newRule;

                // make the rule to store the data via @ <rule>
                newRuleMember.prefix.clear();
                newRuleMember.quantifier = '\0';
                newRuleMember.prefix.is_key_value = true;

                // add data block
                newRule.data_block = AST::DataBlock {AST::RegularDataBlock {AST::make_expr_from_value(AST::CllExprValue {AST::rvalue {AST::At()}})}};
                // add copied member
                newRule.rule_members = {std::make_shared<AST::RuleMember>(newRuleMember)};

                // Store the generated member
                generated.push_back({mem_copy_for_generated, member_ptr});
                toInsert.push_back(std::make_pair(new_name, newRule));
            }
        } else if (member.isGroup()) {
            auto &group = member.getGroup();
            literalsToToken(group.values, count, toInsert, generated);
        } else if (member.isOp()) {
            auto &op = member.getOp();
            literalsToToken(op.options, count, toInsert, generated);
        }
    }
}
void AST::TreePass::literalsToToken(AST::Tree &ast) {
    std::size_t count = 0;
    stdu::vector<std::pair<std::shared_ptr<AST::RuleMember>, std::shared_ptr<AST::RuleMember>>> generated;
    stdu::vector<std::pair<stdu::vector<std::string>, AST::Rule>> toInsert;
    auto &treeMap = ast.getTreeMap();
    AST::TreePass pass(ast);
    for (auto &[name, value] : treeMap) {
        if (corelib::text::isLower(name.back())) {
            pass.literalsToToken(value.rule_members, count, toInsert, generated);
        }
    }
    for (const auto &[name, newRule] : toInsert) {
        treeMap[name] = newRule;
    }
}
bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::String &first, const AST::String &second) {
    if (first.value.size() != second.value.size())
        return first.value.size() > second.value.size();
    return first.value > second.value;
}
bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberBin &first, const AST::RuleMemberBin &second) {
    return first.bin_chars.size() > second.bin_chars.size();
}

bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberHex &first, const AST::RuleMemberHex &second) {
    return first.hex_chars.size() > second.hex_chars.size();
}

bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberName &first, const AST::RuleMemberName &second) {
    auto &treeMap = ast.getTreeMap();
    const auto first_data = treeMap.find(first.name);
    const auto second_data = treeMap.find(second.name);
    if (first_data == treeMap.end())
        throw Error("Not found Rule_name in map: {}", first.name);
    if (second_data == treeMap.end())
        throw Error("Not found Rule_name in map: {}", second.name);
    const auto &first_rules = first_data->second.rule_members;
    const auto &second_rules = second_data->second.rule_members;
    for (std::size_t i = 0; i < first_rules.size() && i < second_rules.size(); ++i) {
        if (*first_rules[i] == *second_rules[i]) {
            continue;
        }
        return prioritySort(ast, *first_rules[i], *second_rules[i]);
    }
    return first_rules.size() > second_rules.size();
}

bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberCsequence &first, const AST::RuleMemberCsequence &second) {
    if (!first.negative && second.negative)
        return true;
    if (first.negative && !second.negative)
        return false;
    return first.characters.size() + first.escaped.size() + first.diapasons.size() >
           second.characters.size() + second.escaped.size() + second.diapasons.size();
}

bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberGroup &first, const AST::RuleMemberGroup &second) {
    for (std::size_t i = 0; i < first.values.size() && i < second.values.size(); ++i) {
        if (*first.values[i] == *second.values[i])
            continue;
        return prioritySort(ast, *first.values[i], *second.values[i]);
    }
    return first.values.size() > second.values.size();
}

bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMemberOp &first, const AST::RuleMemberOp &second) {
    return prioritySort(ast, *first.options.back(), *second.options.back());
}
bool AST::TreePass::prioritySort(const AST::Tree& ast, const AST::RuleMember &first, const AST::RuleMember &second) {
    if (first.isName() && second.isName())
        return prioritySort(ast, first.getName(), second.getName());
    if (first.isGroup() && second.isGroup())
        return prioritySort(ast, first.getGroup(), second.getGroup());
    if (first.isOp() && second.isOp())
        return prioritySort(ast, first.getOp(), second.getOp());
    if (first.isString() && second.isString())
        return prioritySort(ast, first.getString(), second.getString());
    if (first.isEscaped() && second.isEscaped())
        return false;
    if (first.isCsequence() && second.isCsequence())
        return prioritySort(ast, first.getCsequence(), second.getCsequence());
    if (first.isBin() && second.isBin())
        return prioritySort(ast, first.getBin(), second.getBin());
    if (first.isHex() && second.isHex())
        return prioritySort(ast, first.getHex(), second.getHex());
    if (first.isAny() && second.isAny())
        return false;

    if (first.isName()) {
        auto find_it = ast.getTreeMap().find(first.getName().name);
        if (find_it == ast.getTreeMap().end()) {
            throw Error("Not found Rule_name in map");
        }
        const auto &members = find_it->second.rule_members;
        return std::visit([&](const auto &f, const auto &s) -> bool {
            if (members.size() > 1 && getTypes(f) == getTypes(s))
                return false;
            return prioritySort(ast, *members[0], second);
        }, members[0]->value, second.value);
    }
    if (second.isName()){
        auto find_it = ast.getTreeMap().find(second.getName().name);
        if (find_it == ast.getTreeMap().end()) {
            throw Error("Not found Rule_name in map: {}", second.getName().name);
        }
        const auto &members = find_it->second.rule_members;
        return std::visit([&](const auto &f, const auto &s) -> bool {
            if (members.size() > 1 && getTypes(f) == getTypes(s))
                return true;
            return prioritySort(ast, first, *members[0]);
        }, first.value, members[0]->value);
    }
    if (first.isGroup()) {
        auto &dt = first.getGroup();
        if (dt.values.empty())
            throw Error("Empty group");
        return prioritySort(ast, *dt.values[0], second);
    }
    if (second.isGroup()) {
        auto &dt = second.getGroup();
        if (dt.values.empty())
            throw Error("Empty group");
        return prioritySort(ast, first, *dt.values[0]);
    }
    if (first.isOp()) {
        auto &dt = first.getOp();
        if (dt.options.empty())
            throw Error("Empty op");
        return prioritySort(ast, *dt.options.back(), second);
    }
    if (second.isOp()) {
        auto &dt = second.getOp();
        if (dt.options.empty())
            throw Error("Empty op");
        return prioritySort(ast, first, *dt.options[0]);
    }
    return std::visit([&](const auto &f, const auto &s) -> bool {
        stdu::vector<Types> priority_order = {
            Types::string,
            Types::Rule_escaped,
            Types::Rule_csequence,
            Types::Rule_bin,
            Types::Rule_hex,
            Types::Rule_any,
            Types::cll
        };

        auto first_pos = std::find(priority_order.begin(), priority_order.end(), getTypes(f));
        auto second_pos = std::find(priority_order.begin(), priority_order.end(), getTypes(s));
        if (first_pos != priority_order.end() && second_pos != priority_order.end()) {
            return first_pos < second_pos;
        } else if (first_pos != priority_order.end()) {
            return true;  // known comes before unknown
        } else if (second_pos != priority_order.end()) {
            return false; // unknown comes after known
        }
        return false; // both unknown
    }, first.value, second.value);
}
void AST::TreePass::sortByPriority(AST::Tree &ast, AST::RuleMemberOp& options) {
    AST::TreePass pass(ast);
    std::sort(options.options.begin(), options.options.end(), [&](std::shared_ptr<AST::RuleMember> &first, std::shared_ptr<AST::RuleMember> &second) {
        return pass.prioritySort(ast, *first, *second);
    });
}
void AST::TreePass::sortByPriority(AST::Tree &ast, stdu::vector<std::shared_ptr<AST::RuleMember>>& members) {
    for (auto &member_ptr : members) {
        auto &member = *member_ptr;
        if (member.isGroup()) {
            sortByPriority(ast, member.getGroup().values);
        }
        if (member.isOp()) {
            for (auto &option : member.getOp().options) {
                if (option->isGroup()) {
                    sortByPriority(ast, option->getGroup().values);
                }
            }
            sortByPriority(ast, member.getOp());
        }
    }
}
void AST::TreePass::sortByPriority(AST::Tree &ast) {
    for (auto &[name, value] : ast.getTreeMap()) {
        if (corelib::text::isUpper(name.back()))
            continue; // No sense for terminals -> NFA + DFA does not depend on ordering
        if (value.rule_members.empty()) {
            throw Error("Empty rule");
        }
        AST::TreePass pass(ast);
        pass.sortByPriority(ast, value.rule_members);
    }
}
void AST::TreePass::addSpaceToken(AST::Tree &ast) {
    // 1. Ensure 'whitespace' rule exists without overwriting user definitions
    if (!ast.getTreeMap().contains(constants::whitespace)) {
        AST::Rule spaceTokenRule;
        AST::RuleMemberCsequence csequence;
        csequence.escaped = {'t', 'n', 'r', 'v', 'f'};
        csequence.characters = {' '};
        spaceTokenRule.rule_members = {
            std::make_shared<AST::RuleMember>(AST::RuleMember{ .quantifier = '*', .value = csequence })
        };
        ast.getTreeMap()[constants::whitespace] = spaceTokenRule;
    }
    if (!ast.getTreeMap().contains(constants::whitespace_token)) {
        AST::Rule spaceForTokensRule;
        AST::RuleMemberCsequence csequence;
        csequence.escaped = {'t', 'n', 'r', 'v', 'f'};
        csequence.characters = {' '};
        spaceForTokensRule.rule_members = {
            std::make_shared<AST::RuleMember>(AST::RuleMember{ .quantifier = '+', .value = csequence })
        };
        ast.getTreeMap()[constants::whitespace_token] = spaceForTokensRule;
    }
    auto createsExplicitWhitespace = [](auto self, const std::shared_ptr<RuleMember> &mem) -> bool {
        if (!mem) return false;
        if (mem->isNospace() || mem->isAny()) return true;

        if (mem->isGroup()) {
            const auto &vals = mem->getGroup().values;
            if (vals.empty()) return false;
            return self(self, vals.front()) || self(self, vals.back());
        }

        if (mem->isOp()) {
            const auto &opts = mem->getOp().options;
            for (const auto &opt : opts) {
                if (self(self, opt)) return true;
            }
            return false;
        }

        if (mem->isString()) {
            const auto &str = mem->getString().value;
            if (str.empty()) return false;
            auto is_ws = [](char c) {
                return std::find(constants::whitespace_chars.begin(), constants::whitespace_chars.end(), c) != constants::whitespace_chars.end();
            };
            return is_ws(str.front()) || is_ws(str.back());
        }

        if (mem->isCsequence()) {
            const auto &cs = mem->getCsequence();
            if (std::find(cs.characters.begin(), cs.characters.end(), ' ') != cs.characters.end()) return true;
            for (char esc : cs.escaped) {
                if (std::find(constants::whitespace_chars.begin(), constants::whitespace_chars.end(), esc) != constants::whitespace_chars.end()) {
                    return true;
                }
            }
        }

        if (mem->isEscaped()) {
            char decoded = corelib::text::getCharFromEscaped(mem->getEscaped().c);
            if (std::find(constants::whitespace_chars.begin(), constants::whitespace_chars.end(), decoded) != constants::whitespace_chars.end()) {
                return true;
            }
        }
        return false;
    };

    auto processMembers = [&](auto self, stdu::vector<std::shared_ptr<RuleMember>> &rule_members, bool token) -> void {
        stdu::vector<std::shared_ptr<RuleMember>> updated_members;
        updated_members.reserve(rule_members.size() * 2);

        for (std::size_t i = 0; i < rule_members.size(); ++i) {
            auto mem = rule_members[i];

            // Process nested groups recursively
            if (mem->isGroup()) {
                self(self, mem->getGroup().values, token);
            } else if (mem->isOp()) {
                for (auto &opt : mem->getOp().options) {
                    if (opt->isGroup()) {
                        self(self, opt->getGroup().values, token);
                    }
                }
            }

            // Check if either the current member or the preceding member suppresses whitespace
            bool skip_space = createsExplicitWhitespace(createsExplicitWhitespace, mem) ||
                             (i > 0 && createsExplicitWhitespace(createsExplicitWhitespace, rule_members[i - 1]));

            if (i > 0 && !skip_space) {
                auto ws_ref = std::make_shared<AST::RuleMember>(AST::RuleMember{
                    .value = AST::RuleMemberName{.name = {token ? constants::whitespace_token : constants::whitespace}}
                });
                updated_members.push_back(ws_ref);
            }

            updated_members.push_back(mem);
        }

        rule_members = std::move(updated_members);
    };

    // 2. Apply pass to all rules except reserved whitespace rules
    for (auto &[name, rule] : ast.getTreeMap()) {
        if (name == constants::whitespace || name == constants::whitespace_rule || name == constants::whitespace_token)
            continue;
        processMembers(processMembers, rule.rule_members, corelib::text::isUpper(name.back()));
    }
}
void AST::TreePass::removeEmptyRule() {
    removeEmptyRule(*ast);
}
void AST::TreePass::inlineSingleGroups() {
    inlineSingleGroups(*ast);
}
void AST::TreePass::literalsToToken() {
    literalsToToken(*ast);
}
void AST::TreePass::sortByPriority() {
    sortByPriority(*ast);
}
void AST::TreePass::addSpaceToken() {
    addSpaceToken(*ast);
}